--BUSCAR A MAIOR DATA EM QUE HÁ COTAÇÃO PARA O CÓDIGO ANTERIOR
SELECT Max(DATA)
FROM COTACAO
WHERE CODIGO = 'BVMF3'                                        
--RESULTADO: 24/11/2017

--BUSCAR A MENOR DATA EM QUE HÁ COTAÇÃO PARA O NOVO CÓDIGO
SELECT Min(DATA)
FROM COTACAO
WHERE CODIGO = 'B3SA3' 
--RESULTADO: 23/10/2017

--ATUALIZAR A TABELA "ATIVO"
UPDATE ATIVO SET
CODIGO = 'B3SA3',
DESCRICAO = 'B3 SA ON'
WHERE CODIGO = 'BVMF3'

--ATUALIZAR O CAMPO "SEQUENCIAL" DAS COTAÇÕES DO NOVO CÓDIGO SOMANDO O SEU SEQUENCIAL
--COM O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR

--PASSO 1) BUSCAR O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR
SELECT Max(SEQUENCIAL)
FROM COTACAO
WHERE CODIGO = 'SMLE3' 
--RESULTADO: 1113

--PASSO 2) ATUALIZAR O SEQUENCIAL DO CÓDIGO NOVO
UPDATE COTACAO SET    
SEQUENCIAL = SEQUENCIAL + 1113
WHERE CODIGO = 'SMLS3'

--ATUALIZAR O CÓDIGO NA TABELA "COTACAO"
DECLARE @codigoAnterior as nvarchar(6) = 'BVMF3'
DECLARE @codigoNovo as nvarchar(6) = 'B3SA3'

UPDATE COTACAO SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "IFR_DIARIO"
UPDATE IFR_DIARIO SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "MEDIA_DIARIA"  
UPDATE MEDIA_DIARIA SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE VolatilidadeDiaria SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE MediaVolatilidadeDiaria SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      


--ATUALIZAR O CAMPO "SEQUENCIAL" DAS COTAÇÕES SEMANAIS DO NOVO CÓDIGO SOMANDO O SEU SEQUENCIAL
--COM O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR

--PASSO 1) BUSCAR O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR
SELECT Max(SEQUENCIAL)
FROM COTACAO_SEMANAL
WHERE CODIGO = 'SMLE3' 
--RESULTADO: 234

--PASSO 2) ATUALIZAR O SEQUENCIAL DO CÓDIGO NOVO
UPDATE COTACAO_SEMANAL SET    
SEQUENCIAL = SEQUENCIAL + 234
WHERE CODIGO = 'SMLS3'

DECLARE @codigoAnterior as nvarchar(6) = 'BVMF3'
DECLARE @codigoNovo as nvarchar(6) = 'B3SA3'

--ATUALIZAR O CÓDIGO NA TABELA "COTACAO_SEMANAL"   
UPDATE COTACAO_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "IFR_SEMANAL"
UPDATE IFR_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "MEDIA_SEMANAL"     
UPDATE MEDIA_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE VolatilidadeSemanal SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE MediaVolatilidadeSemanal SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      


--ATUALIZA OS SPLITS
UPDATE SPLIT SET 
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--SE FOI CRIADO NOVO CÓDIGO EXCLUIR O ANTERIOR
DELETE
FROM ATIVO
WHERE CODIGO = 'TBLE3'                            


--RECALCULAR OS DADOS PARA O NOVO CÓDIGO A PARTIR DA PRIMEIRA DATA EM QUE HÁ NEGOCIAÇÃO

