--BUSCAR A MAIOR DATA EM QUE HÁ COTAÇÃO PARA O CÓDIGO ANTERIOR
SELECT Max(DATA)
FROM COTACAO
WHERE CODIGO = 'VVAR11'                                        
--RESULTADO: 23/11/2018

--BUSCAR A MENOR DATA EM QUE HÁ COTAÇÃO PARA O NOVO CÓDIGO
SELECT Min(DATA)
FROM COTACAO
WHERE CODIGO = 'VVAR3' 
--RESULTADO: 26/11/2018

--ATUALIZAR A TABELA "ATIVO"
UPDATE ATIVO SET
CODIGO = 'VVAR3',
DESCRICAO = 'VIA VAREJO SA'
WHERE CODIGO = 'VVAR11'

--ATUALIZAR O CAMPO "SEQUENCIAL" DAS COTAÇÕES DO NOVO CÓDIGO SOMANDO O SEU SEQUENCIAL
--COM O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR

--PASSO 1) BUSCAR O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR
SELECT Max(SEQUENCIAL)
FROM COTACAO
WHERE CODIGO = 'VVAR11' 
--RESULTADO: 1220

--PASSO 2) ATUALIZAR O SEQUENCIAL DO CÓDIGO NOVO
UPDATE COTACAO SET    
SEQUENCIAL = SEQUENCIAL + 1220
WHERE CODIGO = 'VVAR3'

--ATUALIZAR O CÓDIGO NA TABELA "COTACAO"
DECLARE @codigoAnterior as nvarchar(6) = 'VVAR11'
DECLARE @codigoNovo as nvarchar(6) = 'VVAR3'

UPDATE COTACAO SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "IFR_DIARIO"
UPDATE IFR_DIARIO SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "MEDIA_DIARIA"  
UPDATE MEDIA_DIARIA SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE VolatilidadeDiaria SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE MediaVolatilidadeDiaria SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      


--ATUALIZAR O CAMPO "SEQUENCIAL" DAS COTAÇÕES SEMANAIS DO NOVO CÓDIGO SOMANDO O SEU SEQUENCIAL
--COM O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR

--PASSO 1) BUSCAR O MAIOR SEQUENCIAL DO CÓDIGO ANTERIOR
SELECT Max(SEQUENCIAL)
FROM COTACAO_SEMANAL
WHERE CODIGO = 'VVAR11' 
--RESULTADO: 258

--PASSO 2) ATUALIZAR O SEQUENCIAL DO CÓDIGO NOVO
UPDATE COTACAO_SEMANAL SET    
SEQUENCIAL = SEQUENCIAL + 258
WHERE CODIGO = 'VVAR3'

DECLARE @codigoAnterior as nvarchar(6) = 'VVAR11'
DECLARE @codigoNovo as nvarchar(6) = 'VVAR3'

--ATUALIZAR O CÓDIGO NA TABELA "COTACAO_SEMANAL"   
UPDATE COTACAO_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "IFR_SEMANAL"
UPDATE IFR_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--ATUALIZAR O CÓDIGO NA TABELA "MEDIA_SEMANAL"     
UPDATE MEDIA_SEMANAL SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE VolatilidadeSemanal SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

UPDATE MediaVolatilidadeSemanal SET
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      


--ATUALIZA OS SPLITS
UPDATE SPLIT SET 
CODIGO = @codigoNovo
WHERE CODIGO = @codigoAnterior      

--SE FOI CRIADO NOVO CÓDIGO EXCLUIR O ANTERIOR
DELETE
FROM ATIVO
WHERE CODIGO = 'VVAR11'                            


--RECALCULAR OS DADOS PARA O NOVO CÓDIGO A PARTIR DA PRIMEIRA DATA EM QUE HÁ NEGOCIAÇÃO

