DELETE
FROM Cotacao
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM IFR_Diario
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM Media_Diaria
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM VolatilidadeDiaria
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM MediaVolatilidadeDiaria
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM MediaNegociosDiaria
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM Cotacao_Semanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM IFR_Semanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM Media_Semanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM VolatilidadeSemanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM MediaVolatilidadeSemanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM MediaNegociosSemanal
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)

DELETE
FROM Split
WHERE Codigo IN (SELECT Codigo FROM ATIVOS_DESCONSIDERADOS)







