CREATE INDEX IX_COTACAO_VALORES ON COTACAO (VALORFECHAMENTO, Titulos_Total, Valor_Total, Negocios_Total) INCLUDE (CODIGO, DATA)

CREATE INDEX IX_IFR_DIARIO_VALORES ON IFR_DIARIO (CODIGO, NUMPERIODOS, VALOR) INCLUDE (DATA)


CREATE INDEX IX_COTACAO_SEMANAL_VALORES ON COTACAO_SEMANAL (VALORFECHAMENTO, Titulos_Total, Valor_Total, Negocios_Total) INCLUDE (CODIGO, DATA)

CREATE INDEX IX_IFR_SEMANAL_VALORES ON IFR_SEMANAL (CODIGO, NUMPERIODOS, VALOR) INCLUDE (DATA)